#!/usr/bin/env bash
# Deploy Aethos PS to a Hostinger VPS that already runs Traefik.
#
# Required local .env values:
#   HOSTINGER_SSH_HOST=<vps-ip-or-hostname>
#
# Optional local .env values:
#   HOSTINGER_SSH_USER=root
#   HOSTINGER_SSH_PORT=22
#   HOSTINGER_APP_DIR=/opt/aethos-ps
#   HOSTINGER_DEPLOY_SOURCE=git
#   HOSTINGER_REPO_URL=git@github.com:owner/repo.git
#   HOSTINGER_BRANCH=main
#   TRAEFIK_ENTRYPOINT=websecure
#   TRAEFIK_CERT_RESOLVER=letsencrypt

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LOCAL_ENV_FILE="${AETHOS_LOCAL_ENV_FILE:-$REPO_ROOT/.env}"
COMPOSE_FILE="docker-compose.hostinger.yml"
PROJECT_NAME="${COMPOSE_PROJECT_NAME:-aethos-ps}"

usage() {
  cat <<'EOF'
Usage:
  scripts/deploy/hostinger-deploy.sh

Required:
  HOSTINGER_SSH_HOST must be set in .env or exported in the shell.

This script:
  1. Filters the local .env into a production runtime env.
  2. Excludes HOSTINGER_API_KEY and HOSTINGER_VM_ID from container env.
  3. SSHes to the VPS and validates Docker + Traefik.
  4. Runs docker compose with docker-compose.hostinger.yml.

Deploy source:
  HOSTINGER_DEPLOY_SOURCE=git    pulls HOSTINGER_BRANCH from HOSTINGER_REPO_URL
  HOSTINGER_DEPLOY_SOURCE=local  rsyncs backend/, frontend/, and compose from here
EOF
}

read_env_value() {
  local key="$1"
  local file="$2"
  if [ ! -f "$file" ]; then
    return 0
  fi
  awk -v key="$key" '
    /^[[:space:]]*#/ { next }
    /^[[:space:]]*$/ { next }
    index($0, key "=") == 1 {
      sub(/^[^=]*=/, "")
      print
      exit
    }
  ' "$file"
}

env_or_file() {
  local key="$1"
  local default_value="${2:-}"
  local value="${!key:-}"
  if [ -n "$value" ]; then
    printf '%s' "$value"
    return
  fi
  value="$(read_env_value "$key" "$LOCAL_ENV_FILE")"
  if [ -n "$value" ]; then
    printf '%s' "$value"
  else
    printf '%s' "$default_value"
  fi
}

require_nonempty() {
  local key="$1"
  local value="$2"
  if [ -z "$value" ]; then
    echo "ERROR: $key is required. Add it to $LOCAL_ENV_FILE or export it." >&2
    exit 1
  fi
}

write_runtime_env() {
  local output_file="$1"
  local app_domain="$2"
  local timesheet_domain="$3"
  local traefik_entrypoint="$4"
  local traefik_cert_resolver="$5"
  local image_tag="$6"
  local database_url="$7"

  if [ ! -f "$LOCAL_ENV_FILE" ]; then
    echo "ERROR: local env file not found: $LOCAL_ENV_FILE" >&2
    exit 1
  fi

  awk '
    /^[[:space:]]*#/ { print; next }
    /^[[:space:]]*$/ { print; next }
    /^HOSTINGER_API_KEY=/ { next }
    /^HOSTINGER_VM_ID=/ { next }
    /^HOSTINGER_APP_DOMAIN=/ { next }
    /^HOSTINGER_TIMESHEET_DOMAIN=/ { next }
    /^HOSTINGER_SSH_/ { next }
    /^HOSTINGER_APP_DIR=/ { next }
    /^HOSTINGER_DEPLOY_SOURCE=/ { next }
    /^HOSTINGER_REPO_URL=/ { next }
    /^HOSTINGER_BRANCH=/ { next }
    /^TRAEFIK_ENTRYPOINT=/ { next }
    /^TRAEFIK_CERT_RESOLVER=/ { next }
    /^AETHOS_IMAGE_TAG=/ { next }
    /^DATABASE_URL=/ { next }
    /^DEBUG=/ { next }
    /^ENVIRONMENT=/ { next }
    /^FRONTEND_BASE_URL=/ { next }
    /^CORS_ORIGINS=/ { next }
    { print }
  ' "$LOCAL_ENV_FILE" > "$output_file"

  cat >> "$output_file" <<EOF

# Hostinger runtime overrides. Generated by scripts/deploy/hostinger-deploy.sh.
DEBUG=false
ENVIRONMENT=production
FRONTEND_BASE_URL=https://${app_domain}
CORS_ORIGINS=https://${app_domain},https://${timesheet_domain}
HOSTINGER_APP_DOMAIN=${app_domain}
HOSTINGER_TIMESHEET_DOMAIN=${timesheet_domain}
TRAEFIK_ENTRYPOINT=${traefik_entrypoint}
TRAEFIK_CERT_RESOLVER=${traefik_cert_resolver}
AETHOS_IMAGE_TAG=${image_tag}
DATABASE_URL=${database_url}
EOF
}

validate_runtime_env() {
  local runtime_env="$1"
  local missing=0
  local required=(
    SUPABASE_URL
    SUPABASE_ANON_KEY
    SUPABASE_SERVICE_ROLE_KEY
    SUPABASE_JWT_SECRET
    OPENROUTER_API_KEY
  )

  for key in "${required[@]}"; do
    if ! awk -F= -v key="$key" 'index($0, key "=") == 1 && length($0) > length(key) + 1 { found=1 } END { exit found ? 0 : 1 }' "$runtime_env"; then
      echo "ERROR: $key is required for production runtime." >&2
      missing=1
    fi
  done

  if awk -F= 'index($0, "HOSTINGER_API_KEY=") == 1 { found=1 } END { exit found ? 0 : 1 }' "$runtime_env"; then
    echo "ERROR: HOSTINGER_API_KEY was found in runtime env; refusing to deploy." >&2
    missing=1
  fi

  if [ "$missing" -ne 0 ]; then
    exit 1
  fi

  if ! awk -F= 'index($0, "DATABASE_URL=") == 1 && length($0) > length("DATABASE_URL=") { found=1 } END { exit found ? 0 : 1 }' "$runtime_env"; then
    echo "WARN: DATABASE_URL is empty; deploy will skip the background worker profile." >&2
  fi
}

wait_for_url() {
  local url="$1"
  local label="$2"

  if ! command -v curl >/dev/null 2>&1; then
    return 0
  fi

  for _ in $(seq 1 18); do
    if curl -fsS --max-time 10 "$url" >/dev/null 2>&1; then
      echo "OK: $label"
      return 0
    fi
    sleep 5
  done

  echo "WARN: $label is not reachable yet: $url" >&2
}

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  usage
  exit 0
fi

APP_DOMAIN="$(env_or_file HOSTINGER_APP_DOMAIN "aethos.ishirock.tech")"
TIMESHEET_DOMAIN="$(env_or_file HOSTINGER_TIMESHEET_DOMAIN "timesheet.aethos.ishirock.tech")"
SSH_HOST="$(env_or_file HOSTINGER_SSH_HOST "")"
SSH_USER="$(env_or_file HOSTINGER_SSH_USER "root")"
SSH_PORT="$(env_or_file HOSTINGER_SSH_PORT "22")"
APP_DIR="$(env_or_file HOSTINGER_APP_DIR "/opt/aethos-ps")"
DEPLOY_SOURCE="$(env_or_file HOSTINGER_DEPLOY_SOURCE "git")"
REPO_URL="$(env_or_file HOSTINGER_REPO_URL "$(git -C "$REPO_ROOT" config --get remote.origin.url || true)")"
BRANCH="$(env_or_file HOSTINGER_BRANCH "main")"
TRAEFIK_ENTRYPOINT="$(env_or_file TRAEFIK_ENTRYPOINT "websecure")"
TRAEFIK_CERT_RESOLVER="$(env_or_file TRAEFIK_CERT_RESOLVER "letsencrypt")"
AETHOS_IMAGE_TAG="$(env_or_file AETHOS_IMAGE_TAG "$(git -C "$REPO_ROOT" rev-parse --short HEAD)")"
DATABASE_URL_VALUE="$(env_or_file DATABASE_URL "")"

if [[ "$DATABASE_URL_VALUE" == *"@db."*"supabase.co:"* ]]; then
  echo "WARN: DATABASE_URL points at the direct Supabase DB host." >&2
  echo "WARN: Docker containers on this VPS cannot reach that IPv6-only host; use the Supabase pooler URL." >&2
  DATABASE_URL_VALUE=""
fi

require_nonempty HOSTINGER_SSH_HOST "$SSH_HOST"
if [ "$DEPLOY_SOURCE" != "git" ] && [ "$DEPLOY_SOURCE" != "local" ]; then
  echo "ERROR: HOSTINGER_DEPLOY_SOURCE must be 'git' or 'local'." >&2
  exit 1
fi
if [ "$DEPLOY_SOURCE" = "git" ]; then
  require_nonempty HOSTINGER_REPO_URL "$REPO_URL"
fi

RUNTIME_ENV="$(mktemp)"
trap 'rm -f "$RUNTIME_ENV"' EXIT

write_runtime_env \
  "$RUNTIME_ENV" \
  "$APP_DOMAIN" \
  "$TIMESHEET_DOMAIN" \
  "$TRAEFIK_ENTRYPOINT" \
  "$TRAEFIK_CERT_RESOLVER" \
  "$AETHOS_IMAGE_TAG" \
  "$DATABASE_URL_VALUE"
validate_runtime_env "$RUNTIME_ENV"

SSH_TARGET="${SSH_USER}@${SSH_HOST}"
SSH_OPTS=(-p "$SSH_PORT")

echo "Deploy target : $SSH_TARGET:$APP_DIR"
echo "Source        : $DEPLOY_SOURCE"
if [ "$DEPLOY_SOURCE" = "git" ]; then
  echo "Branch        : $BRANCH"
fi
echo "Web domain    : https://$APP_DOMAIN"
echo "Timesheet     : https://$TIMESHEET_DOMAIN"

ssh "${SSH_OPTS[@]}" "$SSH_TARGET" bash -s -- "$APP_DIR" <<'REMOTE'
set -euo pipefail

APP_DIR="$1"

if ! command -v docker >/dev/null 2>&1; then
  echo "ERROR: docker is not installed on the VPS." >&2
  exit 1
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "ERROR: docker compose plugin is not installed on the VPS." >&2
  exit 1
fi

if ! docker ps --format '{{.Names}} {{.Image}}' | grep -Ei 'traefik' >/dev/null 2>&1; then
  echo "ERROR: no running Traefik container was found on the VPS." >&2
  exit 1
fi

mkdir -p "$APP_DIR"
REMOTE

if [ "$DEPLOY_SOURCE" = "git" ]; then
  ssh "${SSH_OPTS[@]}" "$SSH_TARGET" bash -s -- "$APP_DIR" "$REPO_URL" "$BRANCH" <<'REMOTE'
set -euo pipefail

APP_DIR="$1"
REPO_URL="$2"
BRANCH="$3"

if [ ! -d "$APP_DIR/.git" ]; then
  rm -rf "$APP_DIR"
  git clone "$REPO_URL" "$APP_DIR"
fi

cd "$APP_DIR"
git fetch --all --prune
git checkout "$BRANCH"
git pull --ff-only origin "$BRANCH"
REMOTE
else
  if ! command -v rsync >/dev/null 2>&1; then
    echo "ERROR: rsync is not installed locally." >&2
    exit 1
  fi
  ssh "${SSH_OPTS[@]}" "$SSH_TARGET" 'command -v rsync >/dev/null 2>&1' || {
    echo "ERROR: rsync is not installed on the VPS." >&2
    exit 1
  }
  ssh "${SSH_OPTS[@]}" "$SSH_TARGET" "mkdir -p '$APP_DIR/backend' '$APP_DIR/frontend' '$APP_DIR/integrations'"
  rsync -az --delete -e "ssh -p $SSH_PORT" \
    --exclude .env \
    "$REPO_ROOT/backend/" "$SSH_TARGET:$APP_DIR/backend/"
  rsync -az --delete -e "ssh -p $SSH_PORT" \
    --exclude node_modules \
    --exclude .angular \
    --exclude dist \
    --exclude test-results \
    --exclude playwright-report \
    --exclude .env \
    "$REPO_ROOT/frontend/" "$SSH_TARGET:$APP_DIR/frontend/"
  rsync -az --delete -e "ssh -p $SSH_PORT" \
    --exclude .env \
    "$REPO_ROOT/integrations/" "$SSH_TARGET:$APP_DIR/integrations/"
  scp -P "$SSH_PORT" "$REPO_ROOT/$COMPOSE_FILE" "$SSH_TARGET:$APP_DIR/$COMPOSE_FILE"
fi

scp -P "$SSH_PORT" "$RUNTIME_ENV" "$SSH_TARGET:$APP_DIR/.env.hostinger"

ssh "${SSH_OPTS[@]}" "$SSH_TARGET" bash -s -- "$APP_DIR" "$PROJECT_NAME" <<'REMOTE'
set -euo pipefail

APP_DIR="$1"
PROJECT_NAME="$2"
cd "$APP_DIR"

PROFILE_ARGS=()
add_profile() {
  local profile="$1"
  local existing
  for existing in "${PROFILE_ARGS[@]}"; do
    if [ "$existing" = "$profile" ]; then
      return
    fi
  done
  PROFILE_ARGS+=(--profile "$profile")
}

if awk -F= 'index($0, "COMPOSE_PROFILES=") == 1 && length($0) > length("COMPOSE_PROFILES=") { found=1 } END { exit found ? 0 : 1 }' .env.hostinger; then
  profiles="$(awk -F= 'index($0, "COMPOSE_PROFILES=") == 1 { print $2; exit }' .env.hostinger)"
  profiles="${profiles//\"/}"
  profiles="${profiles//\'/}"
  IFS=',' read -ra profile_list <<< "$profiles"
  for profile in "${profile_list[@]}"; do
    profile="$(printf '%s' "$profile" | xargs)"
    if [ -n "$profile" ]; then
      add_profile "$profile"
    fi
  done
fi

if awk -F= 'index($0, "DATABASE_URL=") == 1 && length($0) > length("DATABASE_URL=") { found=1 } END { exit found ? 0 : 1 }' .env.hostinger; then
  add_profile worker
else
  echo "WARN: DATABASE_URL is empty; not starting worker profile."
fi

docker compose \
  "${PROFILE_ARGS[@]}" \
  --project-name "$PROJECT_NAME" \
  --env-file .env.hostinger \
  -f docker-compose.hostinger.yml \
  config --quiet

docker compose \
  "${PROFILE_ARGS[@]}" \
  --project-name "$PROJECT_NAME" \
  --env-file .env.hostinger \
  -f docker-compose.hostinger.yml \
  up -d --build --remove-orphans

docker compose \
  "${PROFILE_ARGS[@]}" \
  --project-name "$PROJECT_NAME" \
  --env-file .env.hostinger \
  -f docker-compose.hostinger.yml \
  ps
REMOTE

wait_for_url "https://${APP_DOMAIN}/health" "web health through frontend nginx"
wait_for_url "https://${APP_DOMAIN}/api/v1/ping" "API ping through frontend nginx"
wait_for_url "https://${TIMESHEET_DOMAIN}/health.txt" "timesheet web health"

echo "Deploy command completed."
