#!/usr/bin/env bash
set -euo pipefail

# Install/update the Aethos Nous Hermes profile into the shared host Hermes
# instance. This replaces the old Compose-owned Hermes container for production
# while keeping the Aethos profile versioned in this repository.
#
# Usage on the VPS, from a reviewed Aethos checkout:
#   scripts/deploy/install-aethos-hermes-profile.sh
#   source "$HOME/.hermes/profiles/aethos-nous/aethos-nous.env"
#   hermes -p aethos-nous gateway run

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SOURCE_PROFILE_DIR="$REPO_ROOT/integrations/hermes/aethos-atlas-profile"
SOURCE_MCP_SERVER="$REPO_ROOT/integrations/hermes/aethos_mcp_server.py"

AETHOS_HERMES_PROFILE=${AETHOS_HERMES_PROFILE:-aethos-nous}
HERMES_PROFILES_DIR=${HERMES_PROFILES_DIR:-$HOME/.hermes/profiles}
PROFILE_DIR=${PROFILE_DIR:-$HERMES_PROFILES_DIR/$AETHOS_HERMES_PROFILE}
API_SERVER_PORT=${API_SERVER_PORT:-8643}
AETHOS_HOST_GATEWAY_NETWORK=${AETHOS_HOST_GATEWAY_NETWORK:-bridge}
DEFAULT_API_SERVER_HOST="127.0.0.1"
if command -v docker >/dev/null 2>&1 && docker network inspect "$AETHOS_HOST_GATEWAY_NETWORK" >/dev/null 2>&1; then
  DEFAULT_API_SERVER_HOST="$(docker network inspect "$AETHOS_HOST_GATEWAY_NETWORK" --format '{{(index .IPAM.Config 0).Gateway}}')"
fi
API_SERVER_HOST=${API_SERVER_HOST:-$DEFAULT_API_SERVER_HOST}
API_SERVER_MODEL_NAME=${API_SERVER_MODEL_NAME:-Aethos Nous}
AETHOS_INTERNAL_API_URL=${AETHOS_INTERNAL_API_URL:-http://127.0.0.1:8011}
AETHOS_HERMES_TOOL_TOKEN=${AETHOS_HERMES_TOOL_TOKEN:-}
API_SERVER_KEY=${API_SERVER_KEY:-${HERMES_API_SERVER_KEY:-}}

if ! command -v hermes >/dev/null 2>&1; then
  echo "ERROR: hermes CLI is not installed on this host" >&2
  exit 1
fi

if ! command -v rsync >/dev/null 2>&1; then
  echo "ERROR: rsync is required to install/update profile skills" >&2
  exit 1
fi

if [ ! -d "$SOURCE_PROFILE_DIR" ]; then
  echo "ERROR: source profile missing: $SOURCE_PROFILE_DIR" >&2
  exit 1
fi

if [ ! -f "$SOURCE_MCP_SERVER" ]; then
  echo "ERROR: MCP server missing: $SOURCE_MCP_SERVER" >&2
  exit 1
fi

mkdir -p "$PROFILE_DIR"
rsync -a --delete "$SOURCE_PROFILE_DIR/skills/" "$PROFILE_DIR/skills/"
cp "$SOURCE_PROFILE_DIR/SOUL.md" "$PROFILE_DIR/SOUL.md"
cp "$SOURCE_PROFILE_DIR/mcp.json" "$PROFILE_DIR/mcp.json"
cp "$SOURCE_MCP_SERVER" "$PROFILE_DIR/aethos_mcp_server.py"
chmod 0755 "$PROFILE_DIR/aethos_mcp_server.py"

# The profile config remains source-controlled for the legacy Docker layout. At
# install time we rewrite only the MCP script path so the shared host Hermes
# profile executes the host-profile copy, not /opt/aethos inside a container.
python - "$SOURCE_PROFILE_DIR/config.yaml" "$PROFILE_DIR/config.yaml" "$PROFILE_DIR/aethos_mcp_server.py" <<'PY'
from __future__ import annotations

import sys
from pathlib import Path

source = Path(sys.argv[1])
target = Path(sys.argv[2])
mcp_path = Path(sys.argv[3])
text = source.read_text(encoding="utf-8")
text = text.replace('/opt/aethos/aethos_mcp_server.py', str(mcp_path))
target.write_text(text, encoding="utf-8")
PY

cat > "$PROFILE_DIR/aethos-nous.env" <<ENV
# Generated by scripts/deploy/install-aethos-hermes-profile.sh
# Fill secrets in the host process manager; do not commit this file.
export AETHOS_HERMES_PROFILE="$AETHOS_HERMES_PROFILE"
export API_SERVER_ENABLED="true"
export API_SERVER_HOST="$API_SERVER_HOST"
export API_SERVER_PORT="$API_SERVER_PORT"
export API_SERVER_MODEL_NAME="$API_SERVER_MODEL_NAME"
export API_SERVER_KEY="$API_SERVER_KEY"
export HERMES_API_SERVER_KEY="$API_SERVER_KEY"
export AETHOS_INTERNAL_API_URL="$AETHOS_INTERNAL_API_URL"
export AETHOS_HERMES_TOOL_TOKEN="$AETHOS_HERMES_TOOL_TOKEN"
ENV
chmod 0600 "$PROFILE_DIR/aethos-nous.env"

cat > "$PROFILE_DIR/run-aethos-nous.sh" <<RUN
#!/usr/bin/env bash
set -euo pipefail
source "$PROFILE_DIR/aethos-nous.env"
exec hermes -p "$AETHOS_HERMES_PROFILE" gateway run
RUN
chmod 0750 "$PROFILE_DIR/run-aethos-nous.sh"

cat <<OUT
Installed Aethos Nous Hermes profile:
  profile: $AETHOS_HERMES_PROFILE
  dir:     $PROFILE_DIR
  api:     http://$API_SERVER_HOST:$API_SERVER_PORT
  broker:  $AETHOS_INTERNAL_API_URL

Next:
  1. Set API_SERVER_KEY and AETHOS_HERMES_TOOL_TOKEN in $PROFILE_DIR/aethos-nous.env
  2. Start: $PROFILE_DIR/run-aethos-nous.sh
  3. Point Aethos API at: http://host.docker.internal:$API_SERVER_PORT
OUT
