// Generated by scripts/generate-guides.mjs. Do not edit directly.

export interface GuideHeading {
  id: string;
  label: string;
  level: number;
}

export interface GuideEntry {
  slug: string;
  source: string;
  title: string;
  description: string;
  category: string;
  audience: string;
  featured: boolean;
  status: string;
  readMinutes: number;
  headings: GuideHeading[];
}

export const GUIDE_CATALOG: GuideEntry[] = [
  {
    "slug": "platform-user-guide",
    "source": "docs/user-guide/platform-user-guide.md",
    "title": "Aethos PS platform user guide",
    "description": "The complete operating guide for roles, Nous, Inbox, O2C, P2P, reporting, and controls.",
    "category": "Essentials",
    "audience": "All users",
    "featured": true,
    "status": "Maintained",
    "readMinutes": 48,
    "headings": [
      {
        "id": "1-operating-model",
        "label": "1. Operating Model",
        "level": 2
      },
      {
        "id": "agent-first-workflow-loop",
        "label": "Agent-first workflow loop",
        "level": 3
      },
      {
        "id": "module-quick-map",
        "label": "Module quick map",
        "level": 3
      },
      {
        "id": "signup-password-and-subscription-lifecycle",
        "label": "Signup, password, and subscription lifecycle",
        "level": 3
      },
      {
        "id": "2-roles-and-responsibilities",
        "label": "2. Roles And Responsibilities",
        "level": 2
      },
      {
        "id": "tenant-user-administration",
        "label": "Tenant user administration",
        "level": 3
      },
      {
        "id": "current-approval-policy-matrix",
        "label": "Current approval policy matrix",
        "level": 3
      },
      {
        "id": "3-aethos-nous-and-ai-finance-ops-manager",
        "label": "3. Aethos Nous And AI Finance Ops Manager",
        "level": 2
      },
      {
        "id": "3-1-reliability-and-answer-quality",
        "label": "3.1 Reliability and answer quality",
        "level": 3
      },
      {
        "id": "current-ai-approval-boundary",
        "label": "Current AI approval boundary",
        "level": 3
      },
      {
        "id": "scheduled-finance-ops-manager",
        "label": "Scheduled Finance Ops Manager",
        "level": 3
      },
      {
        "id": "recommended-daily-operating-rhythm",
        "label": "Recommended daily operating rhythm",
        "level": 3
      },
      {
        "id": "4-inbox",
        "label": "4. Inbox",
        "level": 2
      },
      {
        "id": "5-order-to-cash",
        "label": "5. Order To Cash",
        "level": 2
      },
      {
        "id": "6-procure-to-pay",
        "label": "6. Procure To Pay",
        "level": 2
      },
      {
        "id": "7-record-to-report",
        "label": "7. Record To Report",
        "level": 2
      },
      {
        "id": "8-documents",
        "label": "8. Documents",
        "level": 2
      },
      {
        "id": "9-reports-and-management-cockpit",
        "label": "9. Reports And Management Cockpit",
        "level": 2
      },
      {
        "id": "10-settings-agents-and-controls",
        "label": "10. Settings, Agents, And Controls",
        "level": 2
      },
      {
        "id": "11-enterprise-readiness-roadmap",
        "label": "11. Enterprise Readiness Roadmap",
        "level": 2
      },
      {
        "id": "12-scenario-crosswalk",
        "label": "12. Scenario Crosswalk",
        "level": 2
      },
      {
        "id": "13-documentation-and-test-definition-of-done",
        "label": "13. Documentation And Test Definition Of Done",
        "level": 2
      }
    ]
  },
  {
    "slug": "nous-prompt-library",
    "source": "docs/copilot/prompt-library.md",
    "title": "Aethos Nous prompt library",
    "description": "Practical prompts for daily finance operations, collections, close, controls, and demos.",
    "category": "Tutorials",
    "audience": "Finance teams",
    "featured": true,
    "status": "Maintained",
    "readMinutes": 24,
    "headings": [
      {
        "id": "finance-ops-manager",
        "label": "Finance Ops Manager",
        "level": 2
      },
      {
        "id": "order-to-cash",
        "label": "Order To Cash",
        "level": 2
      },
      {
        "id": "collections",
        "label": "Collections",
        "level": 2
      },
      {
        "id": "procure-to-pay",
        "label": "Procure To Pay",
        "level": 2
      },
      {
        "id": "record-to-report",
        "label": "Record To Report",
        "level": 2
      },
      {
        "id": "audit-and-controls",
        "label": "Audit And Controls",
        "level": 2
      },
      {
        "id": "client-and-engagement-onboarding",
        "label": "Client And Engagement Onboarding",
        "level": 2
      },
      {
        "id": "reports-and-documents",
        "label": "Reports And Documents",
        "level": 2
      },
      {
        "id": "settings-and-operations",
        "label": "Settings And Operations",
        "level": 2
      },
      {
        "id": "e2e-scenario-prompt-sets",
        "label": "E2E Scenario Prompt Sets",
        "level": 2
      },
      {
        "id": "prompting-pattern",
        "label": "Prompting Pattern",
        "level": 2
      },
      {
        "id": "demo-guide-v2-live-validation-prompt-set",
        "label": "Demo Guide v2 Live Validation Prompt Set",
        "level": 2
      }
    ]
  },
  {
    "slug": "scenario-demo-guide-v2",
    "source": "docs/DEMO_GUIDE_v2.md",
    "title": "Scenario-based demo guide v2",
    "description": "A full enterprise walkthrough built around realistic advisory clients and finance workflows.",
    "category": "Demo guides",
    "audience": "Demo teams",
    "featured": true,
    "status": "Maintained",
    "readMinutes": 75,
    "headings": [
      {
        "id": "current-product-boundaries",
        "label": "Current Product Boundaries",
        "level": 2
      },
      {
        "id": "the-firm-meridian-advisory-group-llp",
        "label": "The Firm: Meridian Advisory Group LLP",
        "level": 2
      },
      {
        "id": "the-partners-service-line-heads",
        "label": "The Partners & Service Line Heads",
        "level": 3
      },
      {
        "id": "client-portfolio",
        "label": "Client Portfolio",
        "level": 2
      },
      {
        "id": "pre-demo-setup",
        "label": "Pre-Demo Setup",
        "level": 2
      },
      {
        "id": "demo-operating-pattern",
        "label": "Demo Operating Pattern",
        "level": 2
      },
      {
        "id": "getting-started-access-login-and-navigation",
        "label": "Getting Started — Access, Login, and Navigation",
        "level": 2
      },
      {
        "id": "1-reach-the-app-and-sign-in",
        "label": "1. Reach the app and sign in",
        "level": 3
      },
      {
        "id": "2-the-screen-layout",
        "label": "2. The screen layout",
        "level": 3
      },
      {
        "id": "3-navigation-map-what-each-left-nav-item-is-for",
        "label": "3. Navigation map — what each left-nav item is for",
        "level": 3
      },
      {
        "id": "4-suggested-demo-run-order",
        "label": "4. Suggested demo run order",
        "level": 3
      },
      {
        "id": "platform-concepts-explained-read-this-before-demoing",
        "label": "Platform Concepts Explained (Read This Before Demoing)",
        "level": 2
      },
      {
        "id": "a-the-agent-first-operating-model",
        "label": "A. The agent-first operating model",
        "level": 3
      },
      {
        "id": "b-clients-people-and-delivery-structure",
        "label": "B. Clients, people, and delivery structure",
        "level": 3
      },
      {
        "id": "c-order-to-cash-o2c-getting-paid",
        "label": "C. Order-to-Cash (O2C) — getting paid",
        "level": 3
      },
      {
        "id": "d-procure-to-pay-p2p-paying-vendors",
        "label": "D. Procure-to-Pay (P2P) — paying vendors",
        "level": 3
      },
      {
        "id": "e-record-to-report-r2r-the-ledger-and-the-statements",
        "label": "E. Record-to-Report (R2R) — the ledger and the statements",
        "level": 3
      },
      {
        "id": "f-multi-currency",
        "label": "F. Multi-currency",
        "level": 3
      },
      {
        "id": "g-controls-governance-and-audit",
        "label": "G. Controls, governance, and audit",
        "level": 3
      },
      {
        "id": "h-how-nous-stays-fast-reliable-and-trustworthy",
        "label": "H. How Nous stays fast, reliable, and trustworthy",
        "level": 3
      },
      {
        "id": "scenario-coverage-map",
        "label": "Scenario Coverage Map",
        "level": 2
      },
      {
        "id": "1-1-onboarding-a-new-engagement-via-document-drop",
        "label": "1.1 Onboarding a New Engagement via Document Drop",
        "level": 2
      },
      {
        "id": "steps",
        "label": "Steps",
        "level": 3
      },
      {
        "id": "1-2-project-structure-under-the-engagement",
        "label": "1.2 Project Structure Under the Engagement",
        "level": 2
      },
      {
        "id": "1-3-time-entry-cfo-advisory-hours",
        "label": "1.3 Time Entry: CFO Advisory Hours",
        "level": 2
      },
      {
        "id": "1-3a-people-timesheet-approval-and-billable-expenses",
        "label": "1.3A People, Timesheet Approval, and Billable Expenses",
        "level": 2
      },
      {
        "id": "1-4-billing-run-mixed-model-invoice",
        "label": "1.4 Billing Run: Mixed Model Invoice",
        "level": 2
      },
      {
        "id": "1-5-revenue-recognition-retainer-vs-fixed-fee",
        "label": "1.5 Revenue Recognition: Retainer vs Fixed Fee",
        "level": 2
      },
      {
        "id": "1-6-tax-advisory-t-m-with-capped-fee",
        "label": "1.6 Tax Advisory: T&M with Capped Fee",
        "level": 2
      },
      {
        "id": "1-7-o2c-controls-pricing-collections-and-public-invoice-edge-checks",
        "label": "1.7 O2C Controls, Pricing, Collections, and Public Invoice Edge Checks",
        "level": 2
      },
      {
        "id": "2-1-standard-monthly-retainer-billing",
        "label": "2.1 Standard Monthly Retainer Billing",
        "level": 2
      },
      {
        "id": "2-2-annual-accounts-tax-milestone-billing",
        "label": "2.2 Annual Accounts + Tax — Milestone Billing",
        "level": 2
      },
      {
        "id": "2-3-payroll-service-per-employee-billing",
        "label": "2.3 Payroll Service — Per-Employee Billing",
        "level": 2
      },
      {
        "id": "2-4-vendor-bills-brightwater-subcontractor",
        "label": "2.4 Vendor Bills: Brightwater Subcontractor",
        "level": 2
      },
      {
        "id": "2-5-p2p-exception-and-payment-control-edge-checks",
        "label": "2.5 P2P Exception and Payment-Control Edge Checks",
        "level": 2
      },
      {
        "id": "3-1-multi-entity-engagement-structure",
        "label": "3.1 Multi-Entity Engagement Structure",
        "level": 2
      },
      {
        "id": "3-2-bespoke-tax-return-fixed-fee-with-scope-creep-risk",
        "label": "3.2 Bespoke Tax Return — Fixed Fee with Scope Creep Risk",
        "level": 2
      },
      {
        "id": "3-3-trust-accounts-multi-currency-with-singapore-dividend-income",
        "label": "3.3 Trust Accounts: Multi-Currency with Singapore Dividend Income",
        "level": 2
      },
      {
        "id": "3-4-cosec-automated-filing-reminders",
        "label": "3.4 COSEC: Automated Filing Reminders",
        "level": 2
      },
      {
        "id": "4-1-usd-billed-engagement-gbp-base-currency",
        "label": "4.1 USD-Billed Engagement, GBP Base Currency",
        "level": 2
      },
      {
        "id": "4-2-startup-equity-event-milestone-billing-for-fundraise-advisory",
        "label": "4.2 Startup Equity Event: Milestone Billing for Fundraise Advisory",
        "level": 2
      },
      {
        "id": "4-3-cosec-company-changes-per-event-billing",
        "label": "4.3 COSEC: Company Changes → Per-Event Billing",
        "level": 2
      },
      {
        "id": "5-1-ai-assisted-pre-close-checklist",
        "label": "5.1 AI-Assisted Pre-Close Checklist",
        "level": 2
      },
      {
        "id": "5-2-period-lock-in-action",
        "label": "5.2 Period Lock in Action",
        "level": 2
      },
      {
        "id": "5-3-trial-balance-review",
        "label": "5.3 Trial Balance Review",
        "level": 2
      },
      {
        "id": "5-4-management-reporting-snapshot",
        "label": "5.4 Management Reporting Snapshot",
        "level": 2
      },
      {
        "id": "5-5-financial-statement-package-and-year-end-close",
        "label": "5.5 Financial Statement Package and Year-End Close",
        "level": 2
      },
      {
        "id": "5-6-manual-journal-lifecycle-and-r2r-edge-checks",
        "label": "5.6 Manual Journal Lifecycle and R2R Edge Checks",
        "level": 2
      },
      {
        "id": "6-1-daily-finance-ops-check-and-reviewed-work-plan",
        "label": "6.1 Daily Finance Ops Check and Reviewed Work Plan",
        "level": 2
      },
      {
        "id": "6-2-scheduled-finance-ops-manager",
        "label": "6.2 Scheduled Finance Ops Manager",
        "level": 2
      },
      {
        "id": "7-0-tenant-user-administration-and-independent-erp-login",
        "label": "7.0 Tenant User Administration and Independent ERP Login",
        "level": 2
      },
      {
        "id": "7-0a-ai-inference-runtime-and-model-routing",
        "label": "7.0A AI Inference Runtime and Model Routing",
        "level": 2
      },
      {
        "id": "7-1-approval-policy-personas-and-denied-actions",
        "label": "7.1 Approval Policy, Personas, and Denied Actions",
        "level": 2
      },
      {
        "id": "7-2-decision-trail-and-agent-run-ledger",
        "label": "7.2 Decision Trail and Agent Run Ledger",
        "level": 2
      },
      {
        "id": "7-3-operational-health",
        "label": "7.3 Operational Health",
        "level": 2
      },
      {
        "id": "7-4-documents-source-evidence-and-record-scoped-audit",
        "label": "7.4 Documents, Source Evidence, and Record-Scoped Audit",
        "level": 2
      },
      {
        "id": "7-5-configuration-telemetry-and-abuse-path-checks",
        "label": "7.5 Configuration, Telemetry, and Abuse-Path Checks",
        "level": 2
      },
      {
        "id": "what-meridian-39-s-team-doesn-39-t-do-anymore",
        "label": "What Meridian&#39;s team doesn&#39;t do anymore",
        "level": 2
      },
      {
        "id": "the-key-numbers-for-this-demo",
        "label": "The key numbers for this demo",
        "level": 2
      },
      {
        "id": "objection-handlers",
        "label": "Objection Handlers",
        "level": 2
      },
      {
        "id": "appendix-sample-files-for-demo",
        "label": "Appendix: Sample Files for Demo",
        "level": 2
      }
    ]
  },
  {
    "slug": "demo-guide",
    "source": "docs/DEMO_GUIDE.md",
    "title": "Aethos demo guide",
    "description": "The concise engagement-to-cash, procure-to-pay, reporting, and intelligence demo route.",
    "category": "Demo guides",
    "audience": "Demo teams",
    "featured": false,
    "status": "Reference",
    "readMinutes": 11,
    "headings": [
      {
        "id": "before-you-start",
        "label": "Before You Start",
        "level": 2
      },
      {
        "id": "setup-checklist",
        "label": "Setup Checklist",
        "level": 3
      },
      {
        "id": "demo-tenant-state-after-seed-script",
        "label": "Demo Tenant State (after seed script)",
        "level": 3
      },
      {
        "id": "scenario-a-engagement-to-cash-10-min",
        "label": "Scenario A — Engagement to Cash (10 min)",
        "level": 2
      },
      {
        "id": "a1-drop-the-engagement-letter-2-min",
        "label": "A1 — Drop the Engagement Letter (2 min)",
        "level": 3
      },
      {
        "id": "a2-approve-from-inbox-1-min",
        "label": "A2 — Approve from Inbox (1 min)",
        "level": 3
      },
      {
        "id": "a3-log-time-via-chat-2-min",
        "label": "A3 — Log Time via Chat (2 min)",
        "level": 3
      },
      {
        "id": "a4-run-billing-3-min",
        "label": "A4 — Run Billing (3 min)",
        "level": 3
      },
      {
        "id": "a5-show-ar-aging-1-min",
        "label": "A5 — Show AR Aging (1 min)",
        "level": 3
      },
      {
        "id": "scenario-b-procure-to-pay-8-min",
        "label": "Scenario B — Procure to Pay (8 min)",
        "level": 2
      },
      {
        "id": "b1-drop-vendor-invoice-2-min",
        "label": "B1 — Drop Vendor Invoice (2 min)",
        "level": 3
      },
      {
        "id": "b2-approve-the-bill-1-min",
        "label": "B2 — Approve the Bill (1 min)",
        "level": 3
      },
      {
        "id": "b3-pay-bills-3-min",
        "label": "B3 — Pay Bills (3 min)",
        "level": 3
      },
      {
        "id": "b4-show-ap-aging-1-min",
        "label": "B4 — Show AP Aging (1 min)",
        "level": 3
      },
      {
        "id": "scenario-c-record-to-report-8-min",
        "label": "Scenario C — Record to Report (8 min)",
        "level": 2
      },
      {
        "id": "c1-auto-posted-journals-3-min",
        "label": "C1 — Auto-Posted Journals (3 min)",
        "level": 3
      },
      {
        "id": "c2-trial-balance-1-min",
        "label": "C2 — Trial Balance (1 min)",
        "level": 3
      },
      {
        "id": "c3-period-lock-2-min",
        "label": "C3 — Period Lock (2 min)",
        "level": 3
      },
      {
        "id": "c4-reports-overview-2-min",
        "label": "C4 — Reports Overview (2 min)",
        "level": 3
      },
      {
        "id": "scenario-d-agentic-intelligence-5-min",
        "label": "Scenario D — Agentic Intelligence (5 min)",
        "level": 2
      },
      {
        "id": "d1-copilot-financial-q-a-2-min",
        "label": "D1 — Copilot Financial Q&A (2 min)",
        "level": 3
      },
      {
        "id": "d2-inbox-autonomy-promotion-2-min",
        "label": "D2 — Inbox: Autonomy Promotion (2 min)",
        "level": 3
      },
      {
        "id": "d3-source-document-links-1-min",
        "label": "D3 — Source Document Links (1 min)",
        "level": 3
      },
      {
        "id": "scenario-e-multi-currency-settings-5-min",
        "label": "Scenario E — Multi-Currency & Settings (5 min)",
        "level": 2
      },
      {
        "id": "e1-gbp-engagement-2-min",
        "label": "E1 — GBP Engagement (2 min)",
        "level": 3
      },
      {
        "id": "e2-fx-rates-1-min",
        "label": "E2 — FX Rates (1 min)",
        "level": 3
      },
      {
        "id": "e3-settings-2-min",
        "label": "E3 — Settings (2 min)",
        "level": 3
      },
      {
        "id": "key-talking-points-use-throughout",
        "label": "Key Talking Points (use throughout)",
        "level": 2
      },
      {
        "id": "common-questions",
        "label": "Common Questions",
        "level": 2
      },
      {
        "id": "demo-reset",
        "label": "Demo Reset",
        "level": 2
      },
      {
        "id": "platform-overview-card-leave-behind",
        "label": "Platform Overview Card (leave-behind)",
        "level": 2
      }
    ]
  }
];
