-- =============================================================================
-- Migration 0117: Fix post_journal_entry enum casts (issue #372 / #390)
--
-- Found via live-stack testing: the atomic posting RPC from 0107 inserts the
-- enum columns as raw text —
--   * journal_entries.entry_type  (enum journal_entry_type: standard/reversing/auto)
--   * journal_lines.direction     (enum journal_line_direction: DR/CR)
-- Postgres does NOT implicitly cast text -> enum in INSERT ... SELECT, so every
-- call raised: 'column "entry_type" is of type journal_entry_type but expression
-- is of type text'. Result: the atomic posting path (manual + close-agent
-- journals via post_journal) was broken in production. Sub-ledger GL journals are
-- generated by table triggers, not this RPC, so they were unaffected — which is
-- why it went unnoticed until now.
--
-- This recreates the function with explicit enum casts. Everything else is
-- identical to 0107. Idempotent (CREATE OR REPLACE).
-- =============================================================================

BEGIN;

CREATE OR REPLACE FUNCTION post_journal_entry(
    p_entry JSONB,
    p_lines JSONB,
    p_idempotency_key TEXT
)
RETURNS JSONB LANGUAGE plpgsql AS $$
DECLARE
    v_id UUID;
    v_entry JSONB;
BEGIN
    -- Fast idempotent path: already posted under this key → return it.
    IF p_idempotency_key IS NOT NULL THEN
        SELECT to_jsonb(je) INTO v_entry
          FROM journal_entries je
         WHERE je.idempotency_key = p_idempotency_key;
        IF v_entry IS NOT NULL THEN
            RETURN jsonb_build_object('entry', v_entry, 'idempotent_hit', true);
        END IF;
    END IF;

    INSERT INTO journal_entries (
        tenant_id, entry_number, entry_type, original_entry_id, description,
        entry_date, period, reference_type, reference_id, posted_at, created_by,
        reason, idempotency_key
    )
    SELECT
        (p_entry->>'tenant_id')::UUID,
        p_entry->>'entry_number',
        COALESCE(p_entry->>'entry_type', 'auto')::journal_entry_type,
        NULLIF(p_entry->>'original_entry_id', '')::UUID,
        p_entry->>'description',
        (p_entry->>'entry_date')::DATE,
        COALESCE(p_entry->>'period', LEFT(p_entry->>'entry_date', 7)),
        p_entry->>'reference_type',
        NULLIF(p_entry->>'reference_id', '')::UUID,
        COALESCE((p_entry->>'posted_at')::TIMESTAMPTZ, now()),
        NULLIF(p_entry->>'created_by', '')::UUID,
        p_entry->>'reason',
        p_idempotency_key
    ON CONFLICT (idempotency_key) DO NOTHING
    RETURNING id INTO v_id;

    -- Concurrent poster won the race under the same key → return theirs.
    IF v_id IS NULL THEN
        SELECT to_jsonb(je) INTO v_entry
          FROM journal_entries je
         WHERE je.idempotency_key = p_idempotency_key;
        RETURN jsonb_build_object('entry', v_entry, 'idempotent_hit', true);
    END IF;

    INSERT INTO journal_lines (
        tenant_id, journal_entry_id, direction, account_id, amount, currency,
        base_amount, fx_rate_id, description
    )
    SELECT
        (l->>'tenant_id')::UUID,
        v_id,
        (l->>'direction')::journal_line_direction,
        NULLIF(l->>'account_id', '')::UUID,
        (l->>'amount')::NUMERIC,
        l->>'currency',
        (l->>'base_amount')::NUMERIC,
        NULLIF(l->>'fx_rate_id', '')::UUID,
        l->>'description'
      FROM jsonb_array_elements(p_lines) AS l;

    -- Deferred balance trigger validates at COMMIT.
    SELECT to_jsonb(je) INTO v_entry FROM journal_entries je WHERE je.id = v_id;
    RETURN jsonb_build_object('entry', v_entry, 'idempotent_hit', false);
END $$;

COMMENT ON FUNCTION post_journal_entry(JSONB, JSONB, TEXT) IS
    'Atomic, idempotent GL posting (0107 + 0117 enum-cast fix): inserts header + '
    'lines in one transaction, deduped on idempotency_key; balance + completeness '
    'enforced by the deferred triggers.';

COMMIT;
