"""Internal Atlas tool broker for Hermes-powered orchestration.

This router is not a user-facing API. Hermes calls it through a private bearer
token and an opaque context_ref generated by Aethos for each Atlas turn.
"""

from __future__ import annotations

import asyncio
import datetime
import hmac
import re
from collections.abc import Awaitable, Callable
from decimal import Decimal, InvalidOperation
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from pydantic import BaseModel, Field

from app.agents.base import AgentDeps
from app.agents.copilot.graph import CopilotAgent, CopilotDeps
from app.agents.suggestion_writer import write_agent_suggestion
from app.core.config import settings
from app.core.db import get_service_role_client
from app.domain.money import serialise_money
from app.models.engagements import EngagementResponse
from app.services.agents_service import AgentsService
from app.services.atlas_context import AtlasContextError, AtlasToolContext, verify_atlas_context_ref
from app.services.atlas_read_packs import AtlasReadPackService
from app.services.engagements_service import EngagementService
from app.services.o2c_read_service import O2CReadService
from app.services.p2p_read_service import P2PReadService
from app.services.r2r_read_service import R2RReadService
from app.services.reports_service import ReportsService
from supabase import Client

router = APIRouter()
_bearer_scheme = HTTPBearer(auto_error=False)

_READ_SCOPE = "atlas_tools:read"
_ENGAGEMENT_STATUSES = {"active", "draft", "completed", "cancelled", "on_hold"}
_BILLING_ARRANGEMENTS = {
    "time_and_materials",
    "fixed_fee",
    "retainer",
    "retainer_draw",
    "milestone",
    "capped_tm",
    "mixed",
}
_SERVICE_LINES = {"accounting", "tax", "cosec", "payroll", "advisory", "other"}
_PERIOD_RE = re.compile(r"^\d{4}-\d{2}$")


class AtlasToolExecuteRequest(BaseModel):
    """Internal tool execution request from the Hermes MCP bridge."""

    context_ref: str = Field(min_length=1)
    tool_name: str = Field(min_length=1)
    arguments: dict[str, Any] = Field(default_factory=dict)


class AtlasToolExecuteResponse(BaseModel):
    """Internal tool execution response returned to Hermes."""

    tool_name: str
    result: Any


def require_atlas_tool_auth(
    credentials: HTTPAuthorizationCredentials | None = Depends(_bearer_scheme),  # noqa: B008
) -> None:
    """Require the private Hermes-to-Aethos tool broker token."""
    expected = settings.aethos_hermes_tool_token.strip()
    if not expected:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Atlas tool broker is not configured",
        )
    if credentials is None or not hmac.compare_digest(credentials.credentials, expected):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid Atlas tool broker token",
            headers={"WWW-Authenticate": "Bearer"},
        )


@router.post("/execute", response_model=AtlasToolExecuteResponse)
async def execute_atlas_tool(
    payload: AtlasToolExecuteRequest,
    _auth: None = Depends(require_atlas_tool_auth),
    db: Client = Depends(get_service_role_client),  # noqa: B008
) -> AtlasToolExecuteResponse:
    """Execute one allowlisted Aethos tool for Hermes.

    Read tools return compact tenant-scoped read packs. Write-capable tools do
    not grant Hermes direct database mutation; they call existing Aethos policy
    and Inbox review paths.
    """
    try:
        context = verify_atlas_context_ref(
            payload.context_ref,
            required_scope=_READ_SCOPE,
        )
    except AtlasContextError as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid Atlas tool context",
        ) from exc

    tool = _TOOL_DISPATCH.get(payload.tool_name)
    if tool is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Atlas tool is not available",
        )

    result = await tool(db, context, payload.arguments)
    return AtlasToolExecuteResponse(tool_name=payload.tool_name, result=result)


async def _list_engagements(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> list[dict[str, Any]]:
    status_filter = _optional_status(arguments.get("status"))
    limit = _int_arg(arguments.get("limit"), default=25, minimum=1, maximum=100)
    offset = _int_arg(arguments.get("offset"), default=0, minimum=0, maximum=10_000)
    client_id = _optional_string(arguments.get("client_id"), "client_id")

    rows = await EngagementService(db, context.tenant_id).list_engagements(
        status=status_filter,
        client_id=client_id,
        limit=limit,
        offset=offset,
    )
    return [_engagement_to_tool_result(row) for row in rows]


async def _document_intake_read_pack(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    return AtlasReadPackService(db, context.tenant_id).document_intake_read_pack(
        document_id=_optional_string(arguments.get("document_id"), "document_id"),
        filename=_optional_string(arguments.get("filename"), "filename"),
        limit=_int_arg(arguments.get("limit"), default=5, minimum=1, maximum=25),
    )


async def _documents_audit_read_pack(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    return AtlasReadPackService(db, context.tenant_id).documents_audit_read_pack(
        limit=_int_arg(arguments.get("limit"), default=25, minimum=1, maximum=100),
    )


async def _engagement_structure_read_pack(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    return AtlasReadPackService(db, context.tenant_id).engagement_structure_read_pack(
        client_name=_optional_string(arguments.get("client_name"), "client_name"),
        engagement_name=_optional_string(arguments.get("engagement_name"), "engagement_name"),
        limit=_int_arg(arguments.get("limit"), default=25, minimum=1, maximum=100),
    )


async def _resource_delivery_read_pack(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    return AtlasReadPackService(db, context.tenant_id).resource_delivery_read_pack(
        employee_name=_optional_string(arguments.get("employee_name"), "employee_name"),
        project_name=_optional_string(arguments.get("project_name"), "project_name"),
        client_name=_optional_string(arguments.get("client_name"), "client_name"),
        period=_optional_period(arguments.get("period")),
        limit=_int_arg(arguments.get("limit"), default=100, minimum=1, maximum=500),
    )


async def _accounting_decision_trail_read_pack(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    return AtlasReadPackService(db, context.tenant_id).accounting_decision_trail_read_pack(
        limit=_int_arg(arguments.get("limit"), default=10, minimum=1, maximum=25),
    )


async def _operational_health_read_pack(
    db: Client,
    context: AtlasToolContext,
    _arguments: dict[str, Any],
) -> dict[str, Any]:
    return AtlasReadPackService(db, context.tenant_id).operational_health_read_pack()


async def _ar_aging(
    db: Client,
    context: AtlasToolContext,
    _arguments: dict[str, Any],
) -> dict:
    return await asyncio.to_thread(ReportsService(db, context.tenant_id).ar_aging)


async def _ap_aging(
    db: Client,
    context: AtlasToolContext,
    _arguments: dict[str, Any],
) -> dict:
    return await asyncio.to_thread(ReportsService(db, context.tenant_id).ap_aging)


async def _wip(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> list[dict]:
    engagement_id = _optional_string(arguments.get("engagement_id"), "engagement_id")
    service = ReportsService(db, context.tenant_id)
    return await asyncio.to_thread(service.wip, engagement_id=engagement_id)


async def _finance_ops_snapshot(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    engagement_limit = _int_arg(
        arguments.get("engagement_limit"),
        default=10,
        minimum=1,
        maximum=50,
    )
    return {
        "ar_aging": await _ar_aging(db, context, {}),
        "ap_aging": await _ap_aging(db, context, {}),
        "wip": await _wip(db, context, {}),
        "active_engagements": await _list_engagements(
            db,
            context,
            {"status": "active", "limit": engagement_limit},
        ),
    }


async def _finance_ops_control_room(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    return AgentsService(db, context.tenant_id).get_finance_ops_control_room(
        workflow_limit=_int_arg(
            arguments.get("workflow_limit"),
            default=10,
            minimum=1,
            maximum=25,
        ),
        task_limit=_int_arg(
            arguments.get("task_limit"),
            default=10,
            minimum=1,
            maximum=25,
        ),
    )


async def _approval_controls_read_pack(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    try:
        return AgentsService(db, context.tenant_id).get_approval_controls_read_pack(
            user_id=context.user_id,
            inbox_limit=_int_arg(
                arguments.get("inbox_limit"),
                default=10,
                minimum=1,
                maximum=50,
            ),
        )
    except PermissionError as exc:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=str(exc),
        ) from exc


async def _create_finance_ops_action_plan(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    period = _optional_period(arguments.get("period"))
    limit = _int_arg(arguments.get("limit"), default=10, minimum=1, maximum=25)
    tool_input: dict[str, Any] = {"limit": limit}
    if period is not None:
        tool_input["period"] = period

    agent = CopilotAgent(
        deps=CopilotDeps(
            tenant_id=context.tenant_id,
            user_id=context.user_id,
            db_client=db,
        )
    )
    return await agent._execute_tool_with_policy(
        "create_finance_ops_action_plan",
        tool_input,
    )


async def _draft_invoice(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    tool_input = _only_present(
        {
            "engagement_name": _optional_string(arguments.get("engagement_name"), "engagement_name"),
            "engagement_id": _optional_string(arguments.get("engagement_id"), "engagement_id"),
            "period_start": _optional_date(arguments.get("period_start"), "period_start"),
            "period_end": _optional_date(arguments.get("period_end"), "period_end"),
        }
    )
    return await _run_copilot_policy_tool(db, context, "draft_invoice", tool_input)


async def _log_time_entry(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    tool_input = _only_present(
        {
            "project_name": _required_string(arguments.get("project_name"), "project_name"),
            "hours": _decimal_arg(arguments.get("hours"), "hours"),
            "date": _optional_date(arguments.get("date"), "date"),
            "description": _optional_string(arguments.get("description"), "description"),
            "billable": _optional_bool(arguments.get("billable"), default=True),
        }
    )
    return await _run_copilot_policy_tool(db, context, "log_time_entry", tool_input)


async def _create_engagement_review(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    client_name = _required_string(arguments.get("client_name"), "client_name")
    engagement_name = _required_string(arguments.get("engagement_name"), "engagement_name")
    billing_arrangement = _billing_arrangement(
        arguments.get("billing_arrangement"),
        fallback_text=f"{engagement_name} {arguments.get('description') or ''}",
    )
    currency = (_optional_string(arguments.get("currency"), "currency") or "USD").upper()
    if len(currency) != 3:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="currency must be a three-letter code",
        )
    fixed_fee_amount = _optional_money(arguments.get("fixed_fee_amount"))
    cap_amount = _optional_money(arguments.get("cap_amount"))
    retainer_monthly_amount = _optional_money(arguments.get("retainer_monthly_amount"))
    total_value = (
        _optional_money(arguments.get("total_value"))
        or cap_amount
        or fixed_fee_amount
        or retainer_monthly_amount
    )
    service_line = _service_line(
        arguments.get("service_line"),
        fallback_text=f"{engagement_name} {arguments.get('description') or ''}",
    )
    client = _resolve_client(db, context.tenant_id, client_name)
    payload = _only_present(
        {
            "client_name": client.get("name") if client else client_name,
            "client_id": client.get("id") if client else None,
            "engagement_name": engagement_name,
            "billing_arrangement": billing_arrangement,
            "currency": currency,
            "total_value": total_value,
            "fixed_fee_amount": fixed_fee_amount,
            "cap_amount": cap_amount,
            "retainer_monthly_amount": retainer_monthly_amount,
            "start_date": _optional_date(arguments.get("start_date"), "start_date"),
            "end_date": _optional_date(arguments.get("end_date"), "end_date"),
            "service_line": service_line,
            "scope_summary": _optional_string(arguments.get("description"), "description"),
            "first_project_name": _optional_string(
                arguments.get("first_project_name"),
                "first_project_name",
            )
            or engagement_name,
            "first_project_description": _optional_string(
                arguments.get("first_project_description"),
                "first_project_description",
            ),
            "source": "atlas_prompt",
            "requires_inbox_approval": True,
        }
    )
    suggestion = await write_agent_suggestion(
        deps=AgentDeps(
            tenant_id=context.tenant_id,
            user_id=context.user_id,
            db=db,
        ),
        agent_name="engagement_letter_agent",
        action_type="create_engagement_draft",
        document_id=None,
        output=payload,
        confidence=0.84,
        autonomy_level=2,
        confidence_threshold=0.90,
        related_entity_type="client" if client else None,
        related_entity_id=client.get("id") if client else None,
    )
    return {
        "requires_review": True,
        "suggestion_id": suggestion.get("id"),
        "action_type": "create_engagement_draft",
        "review_path": "/app/inbox",
        "prepared_engagement": payload,
        "message": "Prepared an engagement draft and routed it to Inbox for approval.",
    }


async def _o2c_collections_read_pack(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    status_filter = _optional_string(arguments.get("status"), "status")
    return O2CReadService(db, context.tenant_id).collections_read_pack(
        invoice_id=_optional_string(arguments.get("invoice_id"), "invoice_id"),
        invoice_number=_optional_string(
            arguments.get("invoice_number"),
            "invoice_number",
        ),
        client_id=_optional_string(arguments.get("client_id"), "client_id"),
        client_name=_optional_string(arguments.get("client_name"), "client_name"),
        status=status_filter,
        limit=_int_arg(arguments.get("limit"), default=25, minimum=1, maximum=100),
    )


async def _draft_collection_reminders(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    tone = str(arguments.get("tone") or "auto").strip()
    if tone not in {"auto", "gentle", "firm", "final"}:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="tone is not supported",
        )
    tool_input = _only_present(
        {
            "minimum_days_overdue": _int_arg(
                arguments.get("minimum_days_overdue"),
                default=1,
                minimum=1,
                maximum=365,
            ),
            "tone": tone,
            "client_name": _optional_string(arguments.get("client_name"), "client_name"),
            "limit": _int_arg(arguments.get("limit"), default=10, minimum=1, maximum=25),
        }
    )
    return await _run_copilot_policy_tool(
        db,
        context,
        "draft_collection_reminders",
        tool_input,
    )


async def _propose_bill_payment_batch(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    tool_input = _only_present(
        {
            "due_within_days": _int_arg(
                arguments.get("due_within_days"),
                default=7,
                minimum=1,
                maximum=90,
            ),
            "bank_account_label": _optional_string(
                arguments.get("bank_account_label"),
                "bank_account_label",
            ),
        }
    )
    return await _run_copilot_policy_tool(
        db,
        context,
        "propose_bill_payment_batch",
        tool_input,
    )


async def _p2p_payment_risk_read_pack(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    return P2PReadService(db, context.tenant_id).payment_risk_read_pack(
        bill_id=_optional_string(arguments.get("bill_id"), "bill_id"),
        bill_number=_optional_string(arguments.get("bill_number"), "bill_number"),
        vendor_id=_optional_string(arguments.get("vendor_id"), "vendor_id"),
        vendor_name=_optional_string(arguments.get("vendor_name"), "vendor_name"),
        status=_optional_string(arguments.get("status"), "status"),
        due_within_days=_int_arg(
            arguments.get("due_within_days"),
            default=10,
            minimum=0,
            maximum=365,
        ),
        limit=_int_arg(arguments.get("limit"), default=25, minimum=1, maximum=100),
    )


async def _prepare_month_end_close(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    return await _run_copilot_policy_tool(
        db,
        context,
        "prepare_month_end_close",
        {"period": _required_period(arguments.get("period"))},
    )


async def _prepare_year_end_close(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    return await _run_copilot_policy_tool(
        db,
        context,
        "prepare_year_end_close",
        {
            "year": _required_int_arg(
                arguments.get("year"),
                name="year",
                minimum=1900,
                maximum=9999,
            )
        },
    )


async def _generate_financial_statement_package(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    tool_input = _only_present(
        {
            "period_start": _required_period(arguments.get("period_start")),
            "period_end": _optional_period(arguments.get("period_end")),
            "comparison_period_start": _optional_period(
                arguments.get("comparison_period_start")
            ),
            "comparison_period_end": _optional_period(
                arguments.get("comparison_period_end")
            ),
        }
    )
    return await _run_copilot_policy_tool(
        db,
        context,
        "generate_financial_statement_package",
        tool_input,
    )


async def _r2r_management_pack_read_pack(
    db: Client,
    context: AtlasToolContext,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    return R2RReadService(db, context.tenant_id).management_pack_read_pack(
        period=_required_period(arguments.get("period")),
        comparison_period=_optional_period(arguments.get("comparison_period")),
        limit=_int_arg(arguments.get("limit"), default=10, minimum=1, maximum=25),
    )


async def _run_copilot_policy_tool(
    db: Client,
    context: AtlasToolContext,
    tool_name: str,
    tool_input: dict[str, Any],
) -> dict[str, Any]:
    agent = CopilotAgent(
        deps=CopilotDeps(
            tenant_id=context.tenant_id,
            user_id=context.user_id,
            db_client=db,
        )
    )
    return await agent._execute_tool_with_policy(tool_name, tool_input)


def _optional_status(value: Any) -> str | None:
    status_value = _optional_string(value, "status")
    if status_value in {None, "all"}:
        return None
    if status_value not in _ENGAGEMENT_STATUSES:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="status is not supported",
        )
    return status_value


def _optional_string(value: Any, name: str) -> str | None:
    if value is None:
        return None
    if not isinstance(value, str) or not value.strip():
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"{name} must be a non-empty string",
        )
    return value.strip()


def _required_string(value: Any, name: str) -> str:
    parsed = _optional_string(value, name)
    if parsed is None:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"{name} is required",
        )
    return parsed


def _optional_period(value: Any) -> str | None:
    period = _optional_string(value, "period")
    if period is None:
        return None
    normalised = _normalise_period_text(period)
    if normalised is not None:
        return normalised
    if _PERIOD_RE.match(period) is None:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="period must be formatted YYYY-MM or Month YYYY",
        )
    return period


def _required_period(value: Any) -> str:
    period = _optional_period(value)
    if period is None:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="period is required",
        )
    return period


def _optional_date(value: Any, name: str) -> str | None:
    date_value = _optional_string(value, name)
    if date_value is None:
        return None
    try:
        datetime.date.fromisoformat(date_value)
    except ValueError as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"{name} must be formatted YYYY-MM-DD",
        ) from exc
    return date_value


def _optional_bool(value: Any, *, default: bool) -> bool | None:
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        lowered = value.strip().lower()
        if lowered in {"true", "1", "yes", "y"}:
            return True
        if lowered in {"false", "0", "no", "n"}:
            return False
    raise HTTPException(
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        detail="boolean argument is invalid",
    )


def _decimal_arg(value: Any, name: str) -> str:
    if value is None:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"{name} is required",
        )
    try:
        parsed = Decimal(str(value))
    except (InvalidOperation, ValueError) as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"{name} must be a decimal value",
        ) from exc
    if parsed <= 0:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"{name} must be greater than zero",
        )
    return str(parsed)


def _optional_money(value: Any) -> str | None:
    if value in (None, ""):
        return None
    try:
        parsed = Decimal(str(value).replace(",", ""))
    except (InvalidOperation, ValueError) as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="money argument must be a decimal value",
        ) from exc
    if parsed < 0:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="money argument must not be negative",
        )
    return serialise_money(parsed)


def _billing_arrangement(value: Any, *, fallback_text: str) -> str:
    raw = str(value or "").strip().lower().replace(" ", "_").replace("-", "_")
    aliases = {
        "tm": "time_and_materials",
        "t&m": "time_and_materials",
        "fixed": "fixed_fee",
        "fixed_price": "fixed_fee",
        "capped_t&m": "capped_tm",
        "capped_time_and_materials": "capped_tm",
    }
    normalised = aliases.get(raw, raw)
    if normalised in _BILLING_ARRANGEMENTS:
        return normalised
    text = fallback_text.lower()
    if "cap" in text and (
        "time" in text
        or "t&m" in text
        or "hour" in text
        or "advisory" in text
        or "overrun" in text
    ):
        return "capped_tm"
    if "retainer" in text:
        return "retainer"
    if "milestone" in text:
        return "milestone"
    if "fixed" in text:
        return "fixed_fee"
    return "time_and_materials"


def _service_line(value: Any, *, fallback_text: str) -> str:
    raw = str(value or "").strip().lower()
    if raw in _SERVICE_LINES:
        return raw
    text = fallback_text.lower()
    if "tax" in text or "ct600" in text or "corporation" in text:
        return "tax"
    if "cosec" in text or "company secretarial" in text:
        return "cosec"
    if "payroll" in text:
        return "payroll"
    if "advisory" in text or "cfo" in text:
        return "advisory"
    if "account" in text or "book" in text:
        return "accounting"
    return "other"


def _resolve_client(
    db: Client,
    tenant_id: str,
    client_name: str,
) -> dict[str, Any] | None:
    rows = (
        db.table("clients")
        .select("id,name,kind")
        .eq("tenant_id", tenant_id)
        .is_("deleted_at", "null")
        .limit(250)
        .execute()
        .data
        or []
    )
    needle = client_name.lower()
    for row in rows:
        if needle in str(row.get("name") or "").lower():
            return {"id": str(row["id"]), "name": row.get("name"), "kind": row.get("kind")}
    return None


def _normalise_period_text(value: str) -> str | None:
    if _PERIOD_RE.match(value):
        return value
    if re.match(r"^\d{4}-\d{2}-\d{2}$", value):
        return value[:7]
    for fmt in ("%B %Y", "%b %Y"):
        try:
            return datetime.datetime.strptime(value, fmt).strftime("%Y-%m")
        except ValueError:
            continue
    return None


def _int_arg(value: Any, *, default: int, minimum: int, maximum: int) -> int:
    if value is None:
        return default
    if isinstance(value, bool):
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="integer argument must not be boolean",
        )
    try:
        parsed = int(value)
    except (TypeError, ValueError) as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="integer argument is invalid",
        ) from exc
    if parsed < minimum or parsed > maximum:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"integer argument must be between {minimum} and {maximum}",
        )
    return parsed


def _required_int_arg(value: Any, *, name: str, minimum: int, maximum: int) -> int:
    if value is None:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"{name} is required",
        )
    return _int_arg(value, default=minimum, minimum=minimum, maximum=maximum)


def _only_present(payload: dict[str, Any]) -> dict[str, Any]:
    return {key: value for key, value in payload.items() if value is not None}


def _engagement_to_tool_result(row: EngagementResponse) -> dict[str, Any]:
    return row.model_dump(mode="json")


_ToolHandler = Callable[[Client, AtlasToolContext, dict[str, Any]], Awaitable[Any]]
_TOOL_DISPATCH: dict[str, _ToolHandler] = {
    "aethos.documents.intake_read_pack": _document_intake_read_pack,
    "aethos.documents.audit_read_pack": _documents_audit_read_pack,
    "aethos.engagements.list": _list_engagements,
    "aethos.engagements.structure_read_pack": _engagement_structure_read_pack,
    "aethos.engagements.create_review": _create_engagement_review,
    "aethos.finance.ar_aging": _ar_aging,
    "aethos.finance.ap_aging": _ap_aging,
    "aethos.finance.wip": _wip,
    "aethos.delivery.resource_read_pack": _resource_delivery_read_pack,
    "aethos.time.log_entry": _log_time_entry,
    "aethos.finance_ops.snapshot": _finance_ops_snapshot,
    "aethos.finance_ops.control_room": _finance_ops_control_room,
    "aethos.operational_health.read_pack": _operational_health_read_pack,
    "aethos.approval_controls.read_pack": _approval_controls_read_pack,
    "aethos.finance_ops.create_action_plan": _create_finance_ops_action_plan,
    "aethos.o2c.draft_invoice": _draft_invoice,
    "aethos.o2c.collections_read_pack": _o2c_collections_read_pack,
    "aethos.collections.draft_reminders": _draft_collection_reminders,
    "aethos.p2p.payment_risk_read_pack": _p2p_payment_risk_read_pack,
    "aethos.p2p.propose_bill_payment_batch": _propose_bill_payment_batch,
    "aethos.r2r.prepare_month_end_close": _prepare_month_end_close,
    "aethos.r2r.prepare_year_end_close": _prepare_year_end_close,
    "aethos.r2r.generate_financial_statement_package": _generate_financial_statement_package,
    "aethos.r2r.management_pack_read_pack": _r2r_management_pack_read_pack,
    "aethos.r2r.accounting_decision_trail_read_pack": _accounting_decision_trail_read_pack,
}
